# Generated by Django 4.2.15 on 2024-08-27 23:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('cover_image', models.ImageField(upload_to='posts/cover-images/')),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('priority', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
