# Generated by Django 4.2.15 on 2024-08-28 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('name', models.CharField(verbose_name='Nome')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productgalery',
            options={'verbose_name': 'Galeria Produto', 'verbose_name_plural': 'Galerias de Produtos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.model', verbose_name='Modelo'),
        ),
    ]
