# Generated by Django 4.2.15 on 2024-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_model_alter_productgalery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
