# Generated by Django 4.2.15 on 2024-08-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='catalog.product', verbose_name='Produto'),
        ),
    ]
