# Generated by Django 4.2.15 on 2024-08-28 20:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('catalog', '0002_model_alter_productgalery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ddd', models.CharField(max_length=3, verbose_name='DDD')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('number', models.CharField(max_length=6, verbose_name='Numero')),
                ('zipcode', models.CharField(max_length=100, verbose_name='CEP')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('district', models.CharField(max_length=100, verbose_name='CEP')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField()),
                ('file_example', models.FileField(blank=True, null=True, upload_to='', verbose_name='Arte de Exemplo')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaçoes')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.model', verbose_name='Modelo')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.state')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
    ]
