# Generated by Django 4.2.15 on 2024-08-31 12:33

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='uf',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='estado'),
        ),
    ]
