# Generated by Django 4.2.15 on 2024-08-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_quotationinfo_state_quotationinfo_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationinfo',
            old_name='uf',
            new_name='state',
        ),
    ]
