# Generated by Django 4.2.15 on 2024-08-31 12:35

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_uf_quotationinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationinfo',
            name='state',
            field=localflavor.br.models.BRStateField(default='MA', max_length=2, verbose_name='estado'),
            preserve_default=False,
        ),
    ]
